<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Fabric.Policy.Core/Fabric.Policy.Core.csproj" />
    <Content Include="../../policies/policies.json" Link="policies/policies.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
